### ISSUE TITLE
FLOUREON 720P issue

### ISSUE THREAD

**Issue by negrival** [mozilla-iot/onvif-adapter#11]
I have tested this onvif cam: http://www.floureon.com/product-g_121.html

But it doesn't work... When I try to enable onvif-addon the gateway crash, this is the log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webthings-gateway@0.8.1~prestart: webthings-gateway@0.8.1
6 info lifecycle webthings-gateway@0.8.1~start: webthings-gateway@0.8.1
7 verbose lifecycle webthings-gateway@0.8.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle webthings-gateway@0.8.1~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/gateway/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle webthings-gateway@0.8.1~start: CWD: /home/pi/gateway
10 silly lifecycle webthings-gateway@0.8.1~start: Args: [ '-c',
10 silly lifecycle   'webpack --display errors-only && node build/gateway.js' ]
11 silly lifecycle webthings-gateway@0.8.1~start: Returned: code: 139  signal: null
12 info lifecycle webthings-gateway@0.8.1~start: Failed to exec start script
13 verbose stack Error: webthings-gateway@0.8.1 start: `webpack --display errors-only && node build/gateway.js`
13 verbose stack Exit status 139
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid webthings-gateway@0.8.1
15 verbose cwd /home/pi/gateway
16 verbose Linux 4.19.42-v7+
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v8.16.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 139
22 error webthings-gateway@0.8.1 start: `webpack --display errors-only && node build/gateway.js`
22 error Exit status 139
23 error Failed at the webthings-gateway@0.8.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 139, true ]
```

**Comment by negrival** [comment]
I haven't read...
NOTE: If you are installing this add-on in a gateway you built yourself, your system will need to have ffmpeg installed.

And obiusly I have a gateway built myself...
Now have I to install only ffmpeg or also some library(h264, mp3, aac, ...)?

**Comment by mrstegeman** [comment]
You should just need to install `ffmpeg`. That should pull in the required dependencies as well.
