### ISSUE TITLE
HPE_INVALID_HEADER_TOKEN error

### ISSUE THREAD

**Issue by art-0** [mozilla-iot/onvif-adapter#21]
Hi,
I have a IP camera (Overmax OV-Camspot 3.1) and video stream is not working. Log:

> 2019-10-25 11:36:15.631 INFO   : onvif: Unhandled Rejection
2019-10-25 11:36:15.633 ERROR  : onvif: { Error: Parse Error
2019-10-25 11:36:15.635 ERROR  : onvif:     at Socket.socketOnData (_http_client.js:454:20)
2019-10-25 11:36:15.636 ERROR  : onvif:     at emitOne (events.js:116:13)
2019-10-25 11:36:15.637 ERROR  : onvif:     at Socket.emit (events.js:211:7)
2019-10-25 11:36:15.638 ERROR  : onvif:     at addChunk (_stream_readable.js:263:12)
2019-10-25 11:36:15.640 ERROR  : onvif:     at readableAddChunk (_stream_readable.js:250:11)
2019-10-25 11:36:15.641 ERROR  : onvif:     at Socket.Readable.push (_stream_readable.js:208:10)
2019-10-25 11:36:15.642 ERROR  : onvif:     at TCP.onread (net.js:601:20) bytesParsed: 37, code: 'HPE_INVALID_HEADER_TOKEN' }

**Comment by mrstegeman** [comment]
It seems like the camera is returning an invalid HTTP response. Is there any other context in the log for the onvif adapter? It's hard to figure out where the error is coming from.

**Comment by art-0** [comment]
I temporarily bypasses the problem using a different http parser (https://github.com/creationix/http-parser-js). The snapshot works but the stream doesn't. In chrome developer console:

> onvif-305419896:1 Uncaught (in promise) 
D {severity: 2, category: 4, code: 4001, data: Array(1), handled: false}
category: 4
code: 4001
data: ["https://gateway.mozilla-iot.org/media/onvif/onvif-305419896/index.mpd"]
handled: false
severity: 2
__proto__: Object

There are no entries in the gateway logs.

**Comment by mrstegeman** [comment]
Two questions:
1. Does `~/.mozilla-iot/media/onvif/onvif-305419896/index.mpd` exist on the Pi?
2. Are there any `ffmpeg` processes running?

**Comment by art-0** [comment]
Thanks for the answer.

Ad. 1: doesn't exist
Ad.2 yes

I dug deeper and it turned out that the ffmpeg doesn't create the file because:
1. first error: `Could not find codec parameters for stream 0`
- temporary solution: add parameter after ffmpeg: `-rtsp_transport tcp`
2. second error: `Too many packets buffered for output strem 0:0.`
- temporary solution: add parameter before `-f` arg: `-max_muxing_queue_size 1024`

3. third error: `@aac: Too many bits 8832.000000 > 6144 per frame requested, clamping to max`
- temporary solution part 1: it turned out that the stream has audio even though no flag "AudioEncoderConfiguration" is set
- temporary solution part 2: change parameter from `-b:a:0 128k` to `-b:a:0 32k`
- despite the removal of the above errors, there was still no image , only setting the parameter `-an` (no audio) helped. The camera stream works, but it often buffering. I tried to change again the ffmpeg parameters, but I haven't found the solution yet. Buggy camera ;)

**Comment by art-0** [comment]
Maybe buffering can be caused by a slow microsd card, I'll try another one tomorrow.

**Comment by mrstegeman** [comment]
Seems like your camera has some issues!

As for buffering, that can be due slow network speed (upload and download), and/or the SD card.

It would also help to transcode the video at a lower bitrate, but that would require more CPU (versus just copying the video), which could in turn also cause buffering.
