### ISSUE TITLE
Ignoring *.json because it has no messageType

### ISSUE THREAD

**Issue by renatose** [mozilla-iot/onvif-adapter#27]
Hello,

I am not being able to set up my camera after setting its user/pw (that work for the rtsp stream).
The camera was auto-detected and apart from user/pw all was auto filled.

I'm afraid the issue might start on
> 2021-01-04 10:50:13.678 INFO   : onvif-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
> 2021-01-04 10:50:30.704 INFO   : onvif-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType

I'm using a Raspberry Pi B+ as the host system.

Here are the relevant logs:
> 2021-01-04 10:49:57.672 INFO   : Loading add-on: onvif-adapter
> 2021-01-04 10:50:13.220 INFO   : onvif-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
> 2021-01-04 10:50:13.678 INFO   : onvif-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
> 2021-01-04 10:50:30.704 INFO   : onvif-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
> 2021-01-04 10:51:02.750 INFO   : onvif-adapter: Loading add-on onvif-adapter from /home/pi/.webthings/addons/onvif-adapter
> 2021-01-04 10:51:15.890 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:15.905 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:15.922 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:15.931 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:15.946 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:15.962 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:15.977 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:15.990 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:15.998 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:16.006 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:16.015 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:16.024 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:16.033 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:16.041 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:16.051 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:16.059 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:16.067 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:16.076 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:16.084 ERROR  : onvif-adapter: Failed to initialize device at undefined: Error: socket hang up
> 2021-01-04 10:51:18.406 INFO   : onvif-adapter: { urn: 'urn:uuid:2419d68a-2dd2-21b2-a205-44EFBFC76ABF',
> 2021-01-04 10:51:18.426 INFO   : onvif-adapter:   name: 'IPC 23107418',
> 2021-01-04 10:51:18.446 INFO   : onvif-adapter:   address: '192.168.1.145',
> 2021-01-04 10:51:18.456 INFO   : onvif-adapter:   service: 'http://192.168.1.145:5000/onvif/device_service',
> 2021-01-04 10:51:18.474 INFO   : onvif-adapter:   hardware: '',
> 2021-01-04 10:51:18.485 INFO   : onvif-adapter:   location: 'China',
> 2021-01-04 10:51:18.539 INFO   : onvif-adapter:   types: [ 'tdn:NetworkVideoTransmitter' ],
> 2021-01-04 10:51:18.579 INFO   : onvif-adapter:   xaddrs: [ 'http://192.168.1.145:5000/onvif/device_service' ],
> 2021-01-04 10:51:18.599 INFO   : onvif-adapter:   scopes:
> 2021-01-04 10:51:18.622 INFO   : onvif-adapter:    [ 'onvif://www.onvif.org/type/NetworkVideoTransmitter',
> 2021-01-04 10:51:18.643 INFO   : onvif-adapter:      'onvif://www.onvif.org/name/IPC_23107418',
> 2021-01-04 10:51:18.653 INFO   : onvif-adapter:      'onvif://www.onvif.org/location/Country/China' ] }
> 2021-01-04 10:51:18.885 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:18.901 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:18.932 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:18.953 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:18.966 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:18.983 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:18.998 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:19.017 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:19.025 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:19.038 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:19.050 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:19.059 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:19.088 ERROR  : onvif-adapter: { Error: socket hang up
> 2021-01-04 10:51:19.106 ERROR  : onvif-adapter:     at createHangUpError (_http_client.js:332:15)
> 2021-01-04 10:51:19.115 ERROR  : onvif-adapter:     at Socket.socketOnEnd (_http_client.js:435:23)
> 2021-01-04 10:51:19.130 ERROR  : onvif-adapter:     at Socket.emit (events.js:203:15)
> 2021-01-04 10:51:19.143 ERROR  : onvif-adapter:     at endReadableNT (_stream_readable.js:1145:12)
> 2021-01-04 10:51:19.171 ERROR  : onvif-adapter:     at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
> 2021-01-04 10:51:19.188 ERROR  : onvif-adapter: Failed to initialize device at undefined: Error: socket hang up

**Comment by mrstegeman** [comment]
Those first errors are completely normal. As for the failure to connect, does your camera have a different username/password for the RTSP stream and the admin interface? I've encountered cameras that do.

**Comment by renatose** [comment]
I have a chinese brand camera that by default is to be connected with this app: https://play.google.com/store/apps/details?id=com.yoosee (which requires some account and allows the camera to be controlled via the Internet, not just LAN, so I don't trust it too much)
I didn't have much hopes on using it with proper onvif (although it is branded as supporting onvif), but that app has an option to enable and set up a password for NVR connection (hinting at the ONVIF support)
One day by trial and error I could use VLC to connect to it via rtsp://admin:[password]@192.168.1.145/onvif1
That brought up my hopes so I tried to find other ways to connect to it directly: I could successfully connect using https://play.google.com/store/apps/details?id=net.biyee.onvifer
But both https://www.lingodigit.com/onvif_nvc.html and https://gitlab.com/caspermeijn/onvifviewer do not work.
ONVIFER might have some "not on spec" trick to make it work.

**Comment by mrstegeman** [comment]
Yeah, it's really hard to tell. None of these cameras perform quite the same, unfortunately. The ONVIF spec leaves a lot to be desired. I've successfully tested 2 cameras, but have definitely had issues with others. It's hard to tell why your camera is misbehaving at the network level.
